### ISSUE TITLE
feature name wrong

### ISSUE THREAD

**Issue by wds444** [R2D2-2019/manual_control#1]
PS2-input is not a valid feature name, brians statistics will not pick this up.
Please git checkout -b feature-newname and commit that. then remove this branch

**Comment by wds444** [comment]
@TonyvanderKrogt

**Comment by YouriMulder** [comment]
The branch name is still incorrect. The name of the branch is now PS2-controller. Still no feature branch.
https://github.com/R2D2-2019/remote_control/tree/PS2-controller
Can you rename this again?

@TonyvanderKrogt

**Comment by YouriMulder** [comment]
The branch name had been changed to feature-PS2_controller. It is fine now.
